preprocessing:
  FeatureEngineering: df
  drop_columns: ['Sample_ID', 'Label']
  train_path: ../data/raw/train.csv
  unique_value_path: ../data/processed/unique_values.json
  train_path_proc: ../data/processed/train.csv
  trest_path_proc: ../data/processed/test.csv
  test_size: 0.25
  target_column: Label
  random_state: 10

train:
  n_trials: 30
  n_folds: 5
  random_state: 10
  target_column: Label
  model_path: ../models/lgbmOptuna.pkl
  metric_path: ../report/metrics.json
  params_path: ../report/best_params.json
  study_path: ../models/study.joblib

evaluate:
  predict_path: ../data/check/test.csv

endpoints:
  train: 'http://fastapi:8000/train'
  prediction_from_file: 'http://fastapi:8000/predict'
#  train: 'http://localhost:8000/train'
#  prediction_input: 'http://localhost:8000/predict_input'
#  prediction_from_file: 'http://localhost:8000/predict'